// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRoute(arg1:main.RouteInput):Promise<main.AppConfig>;

export function BindTunnel(arg1:main.CloudflareTunnel):Promise<main.AppConfig>;

export function CreateTunnel(arg1:string):Promise<main.AppConfig>;

export function DeleteTunnel(arg1:string,arg2:boolean):Promise<main.AppConfig>;

export function FetchZones():Promise<Array<main.CloudflareZone>>;

export function GetCloudflaredInstallStatus():Promise<main.CloudflaredInstallStatus>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetStatus():Promise<main.RuntimeStatus>;

export function HideMainWindow():Promise<void>;

export function InstallCloudflared():Promise<main.CloudflaredInstallStatus>;

export function ListAllTunnelRoutes():Promise<main.TunnelRouteOverviewResult>;

export function ListTunnels():Promise<Array<main.CloudflareTunnel>>;

export function LoadConfig():Promise<main.AppConfig>;

export function PullRoutesFromCloudflare():Promise<main.SyncResult>;

export function QuitApplication():Promise<void>;

export function RefreshStatus():Promise<main.RuntimeStatus>;

export function RemoveRoute(arg1:string,arg2:boolean):Promise<main.AppConfig>;

export function RestartTunnel():Promise<main.RuntimeStatus>;

export function SaveSettings(arg1:main.SettingsInput):Promise<main.AppConfig>;

export function SetCredentials(arg1:main.CredentialsInput):Promise<main.RuntimeStatus>;

export function ShowMainWindow():Promise<void>;

export function StartTunnel():Promise<main.RuntimeStatus>;

export function StopTunnel():Promise<main.RuntimeStatus>;

export function SyncRoutes():Promise<main.SyncResult>;

export function UpdateRoute(arg1:main.RouteInput):Promise<main.AppConfig>;
