// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRoute(arg1) {
  return window['go']['main']['App']['AddRoute'](arg1);
}

export function BindTunnel(arg1) {
  return window['go']['main']['App']['BindTunnel'](arg1);
}

export function CreateTunnel(arg1) {
  return window['go']['main']['App']['CreateTunnel'](arg1);
}

export function DeleteTunnel(arg1, arg2) {
  return window['go']['main']['App']['DeleteTunnel'](arg1, arg2);
}

export function FetchZones() {
  return window['go']['main']['App']['FetchZones']();
}

export function GetCloudflaredInstallStatus() {
  return window['go']['main']['App']['GetCloudflaredInstallStatus']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HideMainWindow() {
  return window['go']['main']['App']['HideMainWindow']();
}

export function InstallCloudflared() {
  return window['go']['main']['App']['InstallCloudflared']();
}

export function ListAllTunnelRoutes() {
  return window['go']['main']['App']['ListAllTunnelRoutes']();
}

export function ListTunnels() {
  return window['go']['main']['App']['ListTunnels']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function PullRoutesFromCloudflare() {
  return window['go']['main']['App']['PullRoutesFromCloudflare']();
}

export function QuitApplication() {
  return window['go']['main']['App']['QuitApplication']();
}

export function RefreshStatus() {
  return window['go']['main']['App']['RefreshStatus']();
}

export function RemoveRoute(arg1, arg2) {
  return window['go']['main']['App']['RemoveRoute'](arg1, arg2);
}

export function RestartTunnel() {
  return window['go']['main']['App']['RestartTunnel']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetCredentials(arg1) {
  return window['go']['main']['App']['SetCredentials'](arg1);
}

export function ShowMainWindow() {
  return window['go']['main']['App']['ShowMainWindow']();
}

export function StartTunnel() {
  return window['go']['main']['App']['StartTunnel']();
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}

export function SyncRoutes() {
  return window['go']['main']['App']['SyncRoutes']();
}

export function UpdateRoute(arg1) {
  return window['go']['main']['App']['UpdateRoute'](arg1);
}
